### ISSUE TITLE
Page #1 - Inicio

### ISSUE THREAD

**Issue by VCinthia** [VCinthia/TSDS-FrontEnd-Parcial1#1]
[Inicio - Tienda de Cafe](https://tiendadecafe.com.ar/)

**Descripción:**

Maquetación de página de Inicio en HTML y CSS.

**Tareas:**

- [x] Banner principal.
- [x] Nuestros productos.
- [x] Tarjeta 1.
- [x] Tarjeta 2.
- [x] Nuestro Gin.
- [x] Responsive.

---

**Nota:**

- Los componentes compartidos con otras paginas tales como `nav`, `banner inferior` y `footer` se encuentran en la Issue #2 .
- En la carpeta [./styles](https://github.com/VCinthia/TSDS-FrontEnd-Parcial1/tree/main/src/styles) se encuentran los estilos `global.css` y `style.css` para implementar cuando sean necesarios. A su vez, se pueden agregar otros estilos para cada pagina segun sea necesario o hacer un comentario sumandolos de la siguiente manera:

```css

/* --- Body styles --- */
body {
    font-family: var(--font-textos);
    color: var(--color-darkgray);
    background-color: var(--color-white);
    display: flex;
    flex-direction: column;
    position: relative;
    /* min-height: 100vh; */
    margin: 0;
}

```
